spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG

jwt:
  secretKey: mingCoMmerCe123mingCoMmerCe123mingCoMmerCe123
  accessTokenDuration: 1000000000
  refreshTokenDuration: 1000000000000
